### ISSUE TITLE
请问，在运行train.py 跑到validate 报anchor的参数错误，该怎么解决？ 谢谢

### ISSUE THREAD

**Issue by jiqirenno1** [yangfly/sfd.gluoncv#2]
names, maps = validate(net, val_data, ctx, eval_metric)

mxnet.base.MXNetError: Error in operator sfd0_sfdanchorgenerator0_slice_like0: [18:11:18] src/operator/tensor/./matrix_op-inl.h:1292: Check failed: ishape[axis] >= from_shape[axis] (160 vs. 170) Slice axis 2 with size 170exceeds limit of input with size 160

**Comment by yangfly** [comment]
you can set larger input size with input_reshape

**Comment by jiqirenno1** [comment]
Thanks！
